### ISSUE TITLE
Learn command does not work on this lab, cannot run local build (just like in formal-affair-rails-000)

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/join-the-fun-rails#3]
<img width="342" alt="screen shot 2015-09-08 at 12 41 35 pm" src="https://cloud.githubusercontent.com/assets/12770108/9741192/11babccc-5627-11e5-914e-bc698959049a.png">

**Comment by garettarrowood** [comment]
Fixed it?

I "gem install learn.co" inside the directory.  Even though I haven't had to redo this for any lab before.  And it worked. I'll do that for the formal-affairs one too.

**Comment by AnnJohn** [comment]
Thanks @garettarrowood. I'm going to close this issue for now, but please raise another one if you encounter the problem again.

**Comment by sammarcus** [comment]
@garettarrowood when this happened, did you notice if `learn-co` gem was listed when you did `gem list`? this really isn't a bug with the lab per se, sometimes gem sets can get mixed up, especially if there are dependencies and different versions at play. the fix is as simple as reinstalling the gem that isn't cooperating. for what it's worth, I tried reproducing it with this lab and wasn't able to.

**Comment by garettarrowood** [comment]
@sammarcus I did not try "gem list". I didn't know about that command until this moment, or that such a scenario could occur. I'm sure you're right. Thank you for the insight!
